# Generated by Django 4.2.6 on 2023-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("technologies", models.TextField()),
                ("frontend_skills", models.TextField()),
                ("backend_skills", models.TextField()),
                ("databases", models.TextField()),
                ("infrastructure", models.TextField()),
                ("availability", models.CharField(max_length=100)),
            ],
        ),
    ]
